# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c508f4f014342563a7193c8114e90fa21ea1f7bd0bf691aa830d756b227e05ada2589beb245505d2fbeb9e980188044419a78f372f18872a3dbb3cca5ba38ed

test:
  secret_key_base: 188ffd3d137194eb756e9648d8c93e89e23c8c3b4371a6e18b47bc26db8a7a7f46226e0733cdb3f94bd57019bd74dc691929654f95f773d7a1d0400f30786b63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
